version: "3.8"

services:
  app:
    build: .
    ports:
      - 3000:3000
    environment:
      - JWT_SECRET=PRUEBATECNICA
      - PORT=3000
    volumes:
      - .:/usr/api
      - /usr/api/node_modules
